version: "3"
services:
  postal:
    image: alinuxninja/postal
    container_name: postal
    command: run
    ports:
      - "8001:5000"
      - "2525:25"
    depends_on:
      - "mysql"
      - "rabbitmq"
    volumes:
      - ./data/postal/assets:/opt/postal/public/assets
      - ./data/postal/config:/opt/postal/config
    environment:
      - MYSQL_ROOT_PASSWORD=VX3t7n37DcThQW74rt49vkZW78bRtJ8a
      - MYSQL_DATABASE=postal
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=VX3t7n37DcThQW74rt49vkZW78bRtJ8a
      - RABBITMQ_DEFAULT_VHOST=postal
  mysql:
    image: mariadb:10
    container_name: postal_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=VX3t7n37DcThQW74rt49vkZW78bRtJ8a
      - MYSQL_DATABASE=postal
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: postal_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=VX3t7n37DcThQW74rt49vkZW78bRtJ8a
      - RABBITMQ_DEFAULT_VHOST=/postal
